### ISSUE TITLE
EXC_BAD_ACCESS in UIImage+Haneke.swift

### ISSUE THREAD

**Issue by SteveNewhouse** [Haneke/HanekeSwift#115]
Line 56:

``` Swift
if let context = CGBitmapContextCreate(nil, UInt(pixelSize.width), UInt(pixelSize.height), CGImageGetBitsPerComponent(originalImageRef), 0, colorSpace, bitmapInfo) {
```
This is happening during app startup in simulator... run it again, and it usually works. Seen it several times now.  XCode 6.1, iOS 8.1.

Will try to post more info + trace next time I see it.

**Comment by francosolerio** [comment]
I tried the workaround by @nickoneill moving the cache to a property on the application delegate or some view controller, but the problem remains. Every 2/3 launches, while displaying a tableview with many UIImageViews loaded by haneke, the app crashes.

**Comment by fabdarice** [comment]
I still have this problem? Is anyone working on it?

**Comment by coylums** [comment]
I am able to repeat this issue as well.  Will be looking into it further. Everything else is working great.

**Comment by coylums** [comment]
I'm having trouble repeating in the latest beta of XCode (6.2), could be a XCode bug?  Anyone else having issues in the beta?

**Comment by francosolerio** [comment]
I can confirm the bug is present with XCode 6.2 beta 3 (6C101). I'll download beta 4 tomorrow and have some tests.

**Comment by francosolerio** [comment]
Installed beta 4, cleaned build. Rebuilt and run. First two runs produced the same crash.

**Comment by coylums** [comment]
Yeah, it's doing the same for me too. Going to research further.

**Comment by nobunobu** [comment]
Some update about this issue?

**Comment by SteveNewhouse** [comment]
Been searching a bit on this and have found several warnings about using CGBitmapContextCreate outside of the main thread.  Following the stack trace backwards it seems that this crash happens after 
``` 
fetchFromDiskCache
```
dispatches a call as follows:
```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), {
```
AFAIK that does not use the main thread.  So perhaps using:
```
dispatch_get_main_queue()
```
instead would fix this issue.

I'll give it a go over the next few days.

**Comment by SteveNewhouse** [comment]
Early indications are positive for the approach outlined in my previous comment.... here's some back-of-a-napkin test results:

x = crash
o = no crash

Using `dispatch_get_global_queue()`: 
x,x,x,o,o,o,o,o,o,o,o,o,o,x,o,o,o,o,o,o,o,o,o,x,o

Using `dispatch_get_main_queue()`:
o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o,o

In short, during my limited testing, I could not reproduce the crash with the thread change in place.

What I do not comprehend is to what extent using the main queue instead will impact performance and/or defeat the purpose of HanekeSwift to begin with.  Anecdotally, things seemed fine for me.

Try my PR for yourself and see if you get similar results.

**Comment by ashchan** [comment]
@SteveNewhouse This is interesting and awesome :+1: ! I've switched back to SDWebCache in my project, I'd love to try out your PR tomorrow to see if it fixes the crash. Finger crossed :)

**Comment by SteveNewhouse** [comment]
@ashchan oops.. fixed.

**Comment by ashchan** [comment]
@SteveNewhouse Thanks! I've tried your fix for a while day and haven't encountered a single crash yet.

**Comment by fabdarice** [comment]
@SteveNewhouse Hi I'm sorry, to try your fix, do I have to update Alamofire? or do I have to manually do the changes?

**Comment by SteveNewhouse** [comment]
Easiest thing is probably to copy the change- it's a one-liner. See my pull request.

**Comment by SteveNewhouse** [comment]
@hpique Could you try out the proposed fix?

**Comment by hpique** [comment]
@SteveNewhouse Should resume work on Haneke during the weekend. Apologies. Been away for a while.

**Comment by seenickcode** [comment]
+1

**Comment by mirzadelic** [comment]
When this will be fixed on repo?

**Comment by SteveNewhouse** [comment]
@hpique -- do you want to add collaborators to the repo to help vet pull requests & merge once standards are met?

**Comment by ryanio** [comment]
+1

**Comment by ksmandersen** [comment]
Would definitely love to see @SteveNewhouse's changes merged in.

**Comment by dcharbonnier** [comment]
thanks @SteveNewhouse fixed the problem for me too waiting for the merge ;-)

**Comment by hpique** [comment]
@SteveNewhouse @Psidium @gnimmel @broglep-koubachi @ksmandersen @joelchen @nickoneill @phamquochoan @francosolerio @fabdarice @coylums @nobunobu Back in action and hoping to get this fixed. Can any of you provide a bare-bones sample app in which the issue can be reproduced somewhat consistently?

**Comment by tyrauber** [comment]
+1

**Comment by tobiasoleary** [comment]
+1

**Comment by liebeskind** [comment]
+1.

Console output is:
malloc: *** error for object 0x7f9a0630d670: double free
*** set a breakpoint in malloc_error_break to debug

**Comment by jc0x** [comment]
Any traction on the fix for this issue?

**Comment by paulosotu** [comment]
Hi Guys,

Any ETA on  merge?

**Comment by paulosotu** [comment]
Hi guys,

Been investigating this issue a little further and reach a bit of different conclusion than the one achieved by @SteveNewhouse. It seems this issue is a pure thread synchronisation issue on:

 UIImage(data: data)

It seems this isn't thread safe, every-time a crashed occurred it had two thread inside the constructor... Basically my fix for this was to synchronise access to convertFromData by adding a NSLock. I've submitted a pull request:

https://github.com/Haneke/HanekeSwift/pull/207  

@hpique can you check if this can be merged to master?

**Comment by scisci** [comment]
Would like to see this fix merged as well, currently have to fork and patch to get around the bug.

**Comment by DomiR** [comment]
+1 still a problem on iOS9, #207 seems good

**Comment by hpique** [comment]
Finally merged this. Thanks @paulosotu for the pull request.

Worth mentioning that this doesn't fully fix the issue unless you make sure that your whole app uses `UImage.convertFromData` when initialization an image from data.

Hopefully Apple will fix this bug sooner than later and we can remove this workaround.
